# Generated by Django 5.2.3 on 2025-07-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contacts.contact",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of skills"
                    ),
                ),
                (
                    "availability",
                    models.TextField(
                        blank=True,
                        help_text="General availability, e.g., 'Weekends', 'Mon-Fri evenings'",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("INA", "Inactive"),
                            ("PEN", "Pending Approval"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("joined_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["contact__first_name", "contact__last_name"],
            },
        ),
    ]
