# Generated by Django 5.2.3 on 2025-07-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("fundraising", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donation_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount for monetary donations",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[("MON", "Monetary"), ("INK", "In-Kind")],
                        default="MON",
                        max_length=3,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CSH", "Cash"),
                            ("CRD", "Credit/Debit Card"),
                            ("BNK", "Bank Transfer"),
                            ("CHK", "Check"),
                            ("ONL", "Online Platform"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Check if the donor wishes to remain anonymous publicly",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated fundraising campaign, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="fundraising.campaign",
                    ),
                ),
                (
                    "donor_contact",
                    models.ForeignKey(
                        help_text="Contact record of the donor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations_made",
                        to="contacts.contact",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who recorded the donation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-donation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InKindDonationDetail",
            fields=[
                (
                    "donation",
                    models.OneToOneField(
                        help_text="Links to the main donation record of type 'In-Kind'",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="in_kind_details",
                        serialize=False,
                        to="donations.donation",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("GOD", "Good"),
                            ("FAR", "Fair"),
                            ("POR", "Poor"),
                        ],
                        default="GOD",
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "In-Kind Donation Detail",
                "verbose_name_plural": "In-Kind Donation Details",
            },
        ),
    ]
