# Generated by Django 5.2.3 on 2025-07-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Inventory Category",
                "verbose_name_plural": "Inventory Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'pieces', 'kg', 'liters', 'boxes'",
                        max_length=50,
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Quantity at which to reorder",
                        max_digits=10,
                    ),
                ),
                ("last_stocktake_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.inventorycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("ADJ", "Adjustment"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for IN/ADJ+, Negative for OUT/ADJ- if you prefer, or always positive and type dictates logic",
                        max_digits=10,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded the transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "ordering": ["-transaction_date", "item"],
            },
        ),
    ]
