# Generated by Django 5.2.3 on 2025-07-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLA", "Planning"),
                            ("ACT", "Active"),
                            ("COM", "Completed"),
                            ("CAN", "Cancelled"),
                            ("HLD", "On Hold"),
                        ],
                        default="PLA",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member responsible for the campaign",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fundraising Campaign",
                "verbose_name_plural": "Fundraising Campaigns",
                "ordering": ["-start_date", "name"],
            },
        ),
    ]
